model:
  name: bilstm_ner
  hidden_size: 256
  num_layers: 5
  dropout: 0.2

train:
  epochs: 30
  batch_size: 32
  lr: 0.001
  weight_decay: 0.0001  
  patience: 5
  save_path: "checkpoint/bilstm_ner_best.pth"

data:
  train: "data_PhoNER/train_word.json"
  dev: "data_PhoNER/dev_word.json"
  test: "data_PhoNER/test_word.json"