model:
  name: gru
  hidden_size: 256     
  num_layers: 5
  dropout: 0.2

train:
  epochs: 30
  batch_size: 32
  lr: 0.001           
  weight_decay: 0.0001  
  patience: 5
  save_path: "checkpoint/best_gru.pth"

data:
  train: "data_VSFC/UIT-VSFC-train.json"
  dev:   "data_VSFC/UIT-VSFC-dev.json"
  test:  "data_VSFC/UIT-VSFC-test.json"
